{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 3,
   "id": "8ddbcd8d-add6-4305-a581-21a0f63ba7ce",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "C:\\Users\\Hp\\anaconda3\\python.exe\n"
     ]
    }
   ],
   "source": [
    "import sys\n",
    "print(sys.executable)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 4,
   "id": "d2ac7336-adaa-47b2-ba1e-70301f863ccc",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "3.13.5 | packaged by Anaconda, Inc. | (main, Jun 12 2025, 16:37:03) [MSC v.1929 64 bit (AMD64)]\n"
     ]
    }
   ],
   "source": [
    "import sys\n",
    "print(sys.version)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 5,
   "id": "56cfc629-60db-4983-9e2d-013a6462808e",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Collecting google-generativeai\n",
      "  Using cached google_generativeai-0.8.6-py3-none-any.whl.metadata (3.9 kB)\n",
      "Collecting google-ai-generativelanguage==0.6.15 (from google-generativeai)\n",
      "  Using cached google_ai_generativelanguage-0.6.15-py3-none-any.whl.metadata (5.7 kB)\n",
      "Collecting google-api-core (from google-generativeai)\n",
      "  Using cached google_api_core-2.30.3-py3-none-any.whl.metadata (3.1 kB)\n",
      "Collecting google-api-python-client (from google-generativeai)\n",
      "  Using cached google_api_python_client-2.197.0-py3-none-any.whl.metadata (7.0 kB)\n",
      "Collecting google-auth>=2.15.0 (from google-generativeai)\n",
      "  Using cached google_auth-2.53.0-py3-none-any.whl.metadata (5.5 kB)\n",
      "Requirement already satisfied: protobuf in .\\anaconda3\\Lib\\site-packages (from google-generativeai) (6.33.6)\n",
      "Requirement already satisfied: pydantic in .\\anaconda3\\Lib\\site-packages (from google-generativeai) (2.10.3)\n",
      "Requirement already satisfied: tqdm in .\\anaconda3\\Lib\\site-packages (from google-generativeai) (4.67.1)\n",
      "Requirement already satisfied: typing-extensions in .\\anaconda3\\Lib\\site-packages (from google-generativeai) (4.12.2)\n",
      "Collecting proto-plus<2.0.0dev,>=1.22.3 (from google-ai-generativelanguage==0.6.15->google-generativeai)\n",
      "  Using cached proto_plus-1.28.0-py3-none-any.whl.metadata (2.2 kB)\n",
      "Collecting protobuf (from google-generativeai)\n",
      "  Using cached protobuf-5.29.6-cp310-abi3-win_amd64.whl.metadata (592 bytes)\n",
      "Collecting googleapis-common-protos<2.0.0,>=1.63.2 (from google-api-core->google-generativeai)\n",
      "  Using cached googleapis_common_protos-1.75.0-py3-none-any.whl.metadata (8.6 kB)\n",
      "Requirement already satisfied: requests<3.0.0,>=2.20.0 in .\\anaconda3\\Lib\\site-packages (from google-api-core->google-generativeai) (2.32.3)\n",
      "Requirement already satisfied: grpcio<2.0.0,>=1.33.2 in .\\anaconda3\\Lib\\site-packages (from google-api-core[grpc]!=2.0.*,!=2.1.*,!=2.10.*,!=2.2.*,!=2.3.*,!=2.4.*,!=2.5.*,!=2.6.*,!=2.7.*,!=2.8.*,!=2.9.*,<3.0.0dev,>=1.34.1->google-ai-generativelanguage==0.6.15->google-generativeai) (1.80.0)\n",
      "Collecting grpcio-status<2.0.0,>=1.33.2 (from google-api-core[grpc]!=2.0.*,!=2.1.*,!=2.10.*,!=2.2.*,!=2.3.*,!=2.4.*,!=2.5.*,!=2.6.*,!=2.7.*,!=2.8.*,!=2.9.*,<3.0.0dev,>=1.34.1->google-ai-generativelanguage==0.6.15->google-generativeai)\n",
      "  Using cached grpcio_status-1.81.0-py3-none-any.whl.metadata (1.2 kB)\n",
      "Requirement already satisfied: pyasn1-modules>=0.2.1 in .\\anaconda3\\Lib\\site-packages (from google-auth>=2.15.0->google-generativeai) (0.2.8)\n",
      "Requirement already satisfied: cryptography>=38.0.3 in .\\anaconda3\\Lib\\site-packages (from google-auth>=2.15.0->google-generativeai) (44.0.1)\n",
      "INFO: pip is looking at multiple versions of grpcio-status to determine which version is compatible with other requirements. This could take a while.\n",
      "  Using cached grpcio_status-1.80.0-py3-none-any.whl.metadata (1.3 kB)\n",
      "  Using cached grpcio_status-1.78.0-py3-none-any.whl.metadata (1.3 kB)\n",
      "  Using cached grpcio_status-1.76.0-py3-none-any.whl.metadata (1.1 kB)\n",
      "  Using cached grpcio_status-1.75.1-py3-none-any.whl.metadata (1.1 kB)\n",
      "  Using cached grpcio_status-1.75.0-py3-none-any.whl.metadata (1.1 kB)\n",
      "  Using cached grpcio_status-1.74.0-py3-none-any.whl.metadata (1.1 kB)\n",
      "  Using cached grpcio_status-1.73.1-py3-none-any.whl.metadata (1.1 kB)\n",
      "INFO: pip is still looking at multiple versions of grpcio-status to determine which version is compatible with other requirements. This could take a while.\n",
      "  Using cached grpcio_status-1.73.0-py3-none-any.whl.metadata (1.1 kB)\n",
      "  Using cached grpcio_status-1.72.2-py3-none-any.whl.metadata (1.1 kB)\n",
      "  Using cached grpcio_status-1.72.1-py3-none-any.whl.metadata (1.1 kB)\n",
      "  Using cached grpcio_status-1.71.2-py3-none-any.whl.metadata (1.1 kB)\n",
      "Requirement already satisfied: charset-normalizer<4,>=2 in .\\anaconda3\\Lib\\site-packages (from requests<3.0.0,>=2.20.0->google-api-core->google-generativeai) (3.3.2)\n",
      "Requirement already satisfied: idna<4,>=2.5 in .\\anaconda3\\Lib\\site-packages (from requests<3.0.0,>=2.20.0->google-api-core->google-generativeai) (2.10)\n",
      "Requirement already satisfied: urllib3<3,>=1.21.1 in .\\anaconda3\\Lib\\site-packages (from requests<3.0.0,>=2.20.0->google-api-core->google-generativeai) (2.3.0)\n",
      "Requirement already satisfied: certifi>=2017.4.17 in .\\anaconda3\\Lib\\site-packages (from requests<3.0.0,>=2.20.0->google-api-core->google-generativeai) (2025.11.12)\n",
      "Requirement already satisfied: cffi>=1.12 in .\\anaconda3\\Lib\\site-packages (from cryptography>=38.0.3->google-auth>=2.15.0->google-generativeai) (1.17.1)\n",
      "Requirement already satisfied: pycparser in .\\anaconda3\\Lib\\site-packages (from cffi>=1.12->cryptography>=38.0.3->google-auth>=2.15.0->google-generativeai) (2.21)\n",
      "Requirement already satisfied: pyasn1<0.5.0,>=0.4.6 in .\\anaconda3\\Lib\\site-packages (from pyasn1-modules>=0.2.1->google-auth>=2.15.0->google-generativeai) (0.4.8)\n",
      "Collecting httplib2<1.0.0,>=0.19.0 (from google-api-python-client->google-generativeai)\n",
      "  Using cached httplib2-0.31.2-py3-none-any.whl.metadata (2.2 kB)\n",
      "Collecting google-auth-httplib2<1.0.0,>=0.2.0 (from google-api-python-client->google-generativeai)\n",
      "  Using cached google_auth_httplib2-0.4.0-py3-none-any.whl.metadata (3.0 kB)\n",
      "Collecting uritemplate<5,>=3.0.1 (from google-api-python-client->google-generativeai)\n",
      "  Using cached uritemplate-4.2.0-py3-none-any.whl.metadata (2.6 kB)\n",
      "Requirement already satisfied: pyparsing<4,>=3.1 in .\\anaconda3\\Lib\\site-packages (from httplib2<1.0.0,>=0.19.0->google-api-python-client->google-generativeai) (3.2.0)\n",
      "Requirement already satisfied: annotated-types>=0.6.0 in .\\anaconda3\\Lib\\site-packages (from pydantic->google-generativeai) (0.6.0)\n",
      "Requirement already satisfied: pydantic-core==2.27.1 in .\\anaconda3\\Lib\\site-packages (from pydantic->google-generativeai) (2.27.1)\n",
      "Requirement already satisfied: colorama in .\\anaconda3\\Lib\\site-packages (from tqdm->google-generativeai) (0.4.6)\n",
      "Using cached google_generativeai-0.8.6-py3-none-any.whl (155 kB)\n",
      "Using cached google_ai_generativelanguage-0.6.15-py3-none-any.whl (1.3 MB)\n",
      "Using cached google_api_core-2.30.3-py3-none-any.whl (173 kB)\n",
      "Using cached google_auth-2.53.0-py3-none-any.whl (246 kB)\n",
      "Using cached googleapis_common_protos-1.75.0-py3-none-any.whl (300 kB)\n",
      "Using cached grpcio_status-1.71.2-py3-none-any.whl (14 kB)\n",
      "Using cached proto_plus-1.28.0-py3-none-any.whl (50 kB)\n",
      "Using cached protobuf-5.29.6-cp310-abi3-win_amd64.whl (435 kB)\n",
      "Using cached google_api_python_client-2.197.0-py3-none-any.whl (15.3 MB)\n",
      "Using cached google_auth_httplib2-0.4.0-py3-none-any.whl (9.5 kB)\n",
      "Using cached httplib2-0.31.2-py3-none-any.whl (91 kB)\n",
      "Using cached uritemplate-4.2.0-py3-none-any.whl (11 kB)\n",
      "Installing collected packages: uritemplate, protobuf, httplib2, proto-plus, googleapis-common-protos, grpcio-status, google-auth, google-auth-httplib2, google-api-core, google-api-python-client, google-ai-generativelanguage, google-generativeai\n",
      "\n",
      "  Attempting uninstall: protobuf\n",
      "\n",
      "   --- ------------------------------------  1/12 [protobuf]\n",
      "    Found existing installation: protobuf 6.33.6\n",
      "   --- ------------------------------------  1/12 [protobuf]\n",
      "    Uninstalling protobuf-6.33.6:\n",
      "   --- ------------------------------------  1/12 [protobuf]\n",
      "      Successfully uninstalled protobuf-6.33.6\n",
      "   --- ------------------------------------  1/12 [protobuf]\n",
      "   --- ------------------------------------  1/12 [protobuf]\n",
      "   --- ------------------------------------  1/12 [protobuf]\n",
      "   --- ------------------------------------  1/12 [protobuf]\n",
      "   --- ------------------------------------  1/12 [protobuf]\n",
      "   --- ------------------------------------  1/12 [protobuf]\n",
      "   --- ------------------------------------  1/12 [protobuf]\n",
      "   ---------- -----------------------------  3/12 [proto-plus]\n",
      "   ---------- -----------------------------  3/12 [proto-plus]\n",
      "   ------------- --------------------------  4/12 [googleapis-common-protos]\n",
      "   ------------- --------------------------  4/12 [googleapis-common-protos]\n",
      "   ------------- --------------------------  4/12 [googleapis-common-protos]\n",
      "   ---------------- -----------------------  5/12 [grpcio-status]\n",
      "   -------------------- -------------------  6/12 [google-auth]\n",
      "   -------------------- -------------------  6/12 [google-auth]\n",
      "   -------------------- -------------------  6/12 [google-auth]\n",
      "   -------------------- -------------------  6/12 [google-auth]\n",
      "   ----------------------- ----------------  7/12 [google-auth-httplib2]\n",
      "   -------------------------- -------------  8/12 [google-api-core]\n",
      "   -------------------------- -------------  8/12 [google-api-core]\n",
      "   -------------------------- -------------  8/12 [google-api-core]\n",
      "   -------------------------- -------------  8/12 [google-api-core]\n",
      "   -------------------------- -------------  8/12 [google-api-core]\n",
      "   -------------------------- -------------  8/12 [google-api-core]\n",
      "   -------------------------- -------------  8/12 [google-api-core]\n",
      "   -------------------------- -------------  8/12 [google-api-core]\n",
      "   ------------------------------ ---------  9/12 [google-api-python-client]\n",
      "   ------------------------------ ---------  9/12 [google-api-python-client]\n",
      "   ------------------------------ ---------  9/12 [google-api-python-client]\n",
      "   ------------------------------ ---------  9/12 [google-api-python-client]\n",
      "   ------------------------------ ---------  9/12 [google-api-python-client]\n",
      "   ------------------------------ ---------  9/12 [google-api-python-client]\n",
      "   ------------------------------ ---------  9/12 [google-api-python-client]\n",
      "   ------------------------------ ---------  9/12 [google-api-python-client]\n",
      "   ------------------------------ ---------  9/12 [google-api-python-client]\n",
      "   ------------------------------ ---------  9/12 [google-api-python-client]\n",
      "   -------------------------------- ------ 10/12 [google-ai-generativelanguage]\n",
      "   -------------------------------- ------ 10/12 [google-ai-generativelanguage]\n",
      "   -------------------------------- ------ 10/12 [google-ai-generativelanguage]\n",
      "   -------------------------------- ------ 10/12 [google-ai-generativelanguage]\n",
      "   -------------------------------- ------ 10/12 [google-ai-generativelanguage]\n",
      "   -------------------------------- ------ 10/12 [google-ai-generativelanguage]\n",
      "   -------------------------------- ------ 10/12 [google-ai-generativelanguage]\n",
      "   -------------------------------- ------ 10/12 [google-ai-generativelanguage]\n",
      "   -------------------------------- ------ 10/12 [google-ai-generativelanguage]\n",
      "   -------------------------------- ------ 10/12 [google-ai-generativelanguage]\n",
      "   -------------------------------- ------ 10/12 [google-ai-generativelanguage]\n",
      "   -------------------------------- ------ 10/12 [google-ai-generativelanguage]\n",
      "   -------------------------------- ------ 10/12 [google-ai-generativelanguage]\n",
      "   -------------------------------- ------ 10/12 [google-ai-generativelanguage]\n",
      "   -------------------------------- ------ 10/12 [google-ai-generativelanguage]\n",
      "   -------------------------------- ------ 10/12 [google-ai-generativelanguage]\n",
      "   -------------------------------- ------ 10/12 [google-ai-generativelanguage]\n",
      "   -------------------------------- ------ 10/12 [google-ai-generativelanguage]\n",
      "   -------------------------------- ------ 10/12 [google-ai-generativelanguage]\n",
      "   -------------------------------- ------ 10/12 [google-ai-generativelanguage]\n",
      "   -------------------------------- ------ 10/12 [google-ai-generativelanguage]\n",
      "   -------------------------------- ------ 10/12 [google-ai-generativelanguage]\n",
      "   -------------------------------- ------ 10/12 [google-ai-generativelanguage]\n",
      "   -------------------------------- ------ 10/12 [google-ai-generativelanguage]\n",
      "   ------------------------------------ --- 11/12 [google-generativeai]\n",
      "   ------------------------------------ --- 11/12 [google-generativeai]\n",
      "   ------------------------------------ --- 11/12 [google-generativeai]\n",
      "   ---------------------------------------- 12/12 [google-generativeai]\n",
      "\n",
      "Successfully installed google-ai-generativelanguage-0.6.15 google-api-core-2.30.3 google-api-python-client-2.197.0 google-auth-2.53.0 google-auth-httplib2-0.4.0 google-generativeai-0.8.6 googleapis-common-protos-1.75.0 grpcio-status-1.71.2 httplib2-0.31.2 proto-plus-1.28.0 protobuf-5.29.6 uritemplate-4.2.0\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.\n",
      "tensorflow 2.21.0 requires protobuf<8.0.0,>=6.31.1, but you have protobuf 5.29.6 which is incompatible.\n"
     ]
    }
   ],
   "source": [
    "import sys\n",
    "!{sys.executable} -m pip install -U google-generativeai"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 6,
   "id": "9c4c424b-fb34-49ea-9db0-76fa855b0c41",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Success\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "C:\\Users\\Hp\\AppData\\Local\\Temp\\ipykernel_8112\\1090332968.py:1: FutureWarning: \n",
      "\n",
      "All support for the `google.generativeai` package has ended. It will no longer be receiving \n",
      "updates or bug fixes. Please switch to the `google.genai` package as soon as possible.\n",
      "See README for more details:\n",
      "\n",
      "https://github.com/google-gemini/deprecated-generative-ai-python/blob/main/README.md\n",
      "\n",
      "  import google.generativeai as genai\n"
     ]
    }
   ],
   "source": [
    "import google.generativeai as genai\n",
    "print(\"Success\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 11,
   "id": "e655250f-5236-47a5-abd1-f15e93244ea9",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "models/gemini-2.5-flash\n",
      "models/gemini-2.5-pro\n",
      "models/gemini-2.0-flash\n",
      "models/gemini-2.0-flash-001\n",
      "models/gemini-2.0-flash-lite-001\n",
      "models/gemini-2.0-flash-lite\n",
      "models/gemini-2.5-flash-preview-tts\n",
      "models/gemini-2.5-pro-preview-tts\n",
      "models/gemma-4-26b-a4b-it\n",
      "models/gemma-4-31b-it\n",
      "models/gemini-flash-latest\n",
      "models/gemini-flash-lite-latest\n",
      "models/gemini-pro-latest\n",
      "models/gemini-2.5-flash-lite\n",
      "models/gemini-2.5-flash-image\n",
      "models/gemini-3-pro-preview\n",
      "models/gemini-3-flash-preview\n",
      "models/gemini-3.1-pro-preview\n",
      "models/gemini-3.1-pro-preview-customtools\n",
      "models/gemini-3.1-flash-lite-preview\n",
      "models/gemini-3.1-flash-lite\n",
      "models/gemini-3-pro-image-preview\n",
      "models/gemini-3-pro-image\n",
      "models/nano-banana-pro-preview\n",
      "models/gemini-3.1-flash-image-preview\n",
      "models/gemini-3.1-flash-image\n",
      "models/gemini-3.5-flash\n",
      "models/lyria-3-clip-preview\n",
      "models/lyria-3-pro-preview\n",
      "models/gemini-3.1-flash-tts-preview\n",
      "models/gemini-robotics-er-1.5-preview\n",
      "models/gemini-robotics-er-1.6-preview\n",
      "models/gemini-2.5-computer-use-preview-10-2025\n",
      "models/antigravity-preview-05-2026\n",
      "models/deep-research-max-preview-04-2026\n",
      "models/deep-research-preview-04-2026\n",
      "models/deep-research-pro-preview-12-2025\n"
     ]
    }
   ],
   "source": [
    "import google.generativeai as genai\n",
    "\n",
    "API_KEY = \"AQ.Ab8RN6Lobh-oQwbNcq-ZdCtk0BklRJwSws4cnEV1Qxa0SU9z1Q\"\n",
    "\n",
    "genai.configure(api_key=API_KEY)\n",
    "\n",
    "for model in genai.list_models():\n",
    "    if \"generateContent\" in model.supported_generation_methods:\n",
    "        print(model.name)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 13,
   "id": "2e8bd674-b7b0-483c-b78f-5a12a543e321",
   "metadata": {},
   "outputs": [],
   "source": [
    "import tkinter as tk\n",
    "from tkinter import scrolledtext\n",
    "import google.generativeai as genai"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 14,
   "id": "4d26cbe7-678a-4f8e-a112-9a41a806c94d",
   "metadata": {},
   "outputs": [],
   "source": [
    "model = genai.GenerativeModel(\"gemini-2.5-flash\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 15,
   "id": "f77da317-f1c1-444b-b6be-da1003fe6dcb",
   "metadata": {},
   "outputs": [],
   "source": [
    "import tkinter as tk\n",
    "from tkinter import scrolledtext\n",
    "import google.generativeai as genai"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 16,
   "id": "8a45f8f7-ed6e-4471-b25f-3479a826c870",
   "metadata": {},
   "outputs": [],
   "source": [
    "API_KEY = \"AQ.Ab8RN6Lobh-oQwbNcq-ZdCtk0BklRJwSws4cnEV1Qxa0SU9z1Q\"\n",
    "\n",
    "genai.configure(api_key=API_KEY)\n",
    "\n",
    "model = genai.GenerativeModel(\"gemini-2.5-flash\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 17,
   "id": "33417c77-f28c-46e3-9502-9654bf0c7a01",
   "metadata": {},
   "outputs": [],
   "source": [
    "def get_ai_response(prompt):\n",
    "\n",
    "    try:\n",
    "\n",
    "        response = model.generate_content(prompt)\n",
    "\n",
    "        return response.text\n",
    "\n",
    "    except Exception as e:\n",
    "\n",
    "        return f\"Error: {e}\""
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 18,
   "id": "e80dd9d2-d4b6-4c15-9d38-f57e152674b0",
   "metadata": {},
   "outputs": [],
   "source": [
    "def send_message():\n",
    "\n",
    "    user_message = entry_box.get().strip()\n",
    "\n",
    "    if not user_message:\n",
    "        return\n",
    "\n",
    "    chat_area.config(state=tk.NORMAL)\n",
    "\n",
    "    chat_area.insert(\n",
    "        tk.END,\n",
    "        f\"You: {user_message}\\n\\n\"\n",
    "    )\n",
    "\n",
    "    entry_box.delete(0, tk.END)\n",
    "\n",
    "    root.update()\n",
    "\n",
    "    bot_response = get_ai_response(user_message)\n",
    "\n",
    "    chat_area.insert(\n",
    "        tk.END,\n",
    "        f\"Bot: {bot_response}\\n\\n\"\n",
    "    )\n",
    "\n",
    "    chat_area.config(state=tk.DISABLED)\n",
    "\n",
    "    chat_area.yview(tk.END)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 19,
   "id": "ef1cd1eb-db7f-4ac6-807f-b3d0e8c35052",
   "metadata": {},
   "outputs": [],
   "source": [
    "def clear_chat():\n",
    "\n",
    "    chat_area.config(state=tk.NORMAL)\n",
    "\n",
    "    chat_area.delete(1.0, tk.END)\n",
    "\n",
    "    chat_area.config(state=tk.DISABLED)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "43fcf0ae-234d-4f45-b6a0-a1525b9f0290",
   "metadata": {},
   "outputs": [],
   "source": [
    "root = tk.Tk()\n",
    "\n",
    "root.title(\"Gemini AI Chatbot\")\n",
    "\n",
    "root.geometry(\"900x700\")\n",
    "\n",
    "title = tk.Label(\n",
    "    root,\n",
    "    text=\"Gemini AI Chatbot\",\n",
    "    font=(\"Arial\", 18, \"bold\")\n",
    ")\n",
    "\n",
    "title.pack(pady=10)\n",
    "\n",
    "chat_area = scrolledtext.ScrolledText(\n",
    "    root,\n",
    "    width=100,\n",
    "    height=25,\n",
    "    font=(\"Arial\", 11)\n",
    ")\n",
    "\n",
    "chat_area.pack(padx=10, pady=10)\n",
    "\n",
    "chat_area.config(state=tk.DISABLED)\n",
    "\n",
    "entry_box = tk.Entry(\n",
    "    root,\n",
    "    width=70,\n",
    "    font=(\"Arial\", 12)\n",
    ")\n",
    "\n",
    "entry_box.pack(side=tk.LEFT, padx=10, pady=10)\n",
    "\n",
    "entry_box.bind(\"<Return>\", lambda event: send_message())\n",
    "\n",
    "send_btn = tk.Button(\n",
    "    root,\n",
    "    text=\"Send\",\n",
    "    command=send_message,\n",
    "    width=15\n",
    ")\n",
    "\n",
    "send_btn.pack(side=tk.LEFT)\n",
    "\n",
    "clear_btn = tk.Button(\n",
    "    root,\n",
    "    text=\"Clear Chat\",\n",
    "    command=clear_chat,\n",
    "    width=15\n",
    ")\n",
    "\n",
    "clear_btn.pack(side=tk.LEFT)\n",
    "\n",
    "root.mainloop()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 21,
   "id": "496e78ba-c277-4d79-a40e-a3c649bacc3c",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "AI stands for **Artificial Intelligence**.\n",
      "\n",
      "At its core, **AI is a field of computer science dedicated to creating machines that can perform tasks that typically require human intelligence.**\n",
      "\n",
      "It's about developing computer systems that can:\n",
      "\n",
      "1.  **Learn:** Acquire knowledge and skills from experience or data, adapting and improving over time without being explicitly programmed for every scenario.\n",
      "2.  **Reason:** Use logic, rules, or learned patterns to draw conclusions, make predictions, and solve problems.\n",
      "3.  **Perceive:** Interpret information from the world, whether it's images (computer vision), speech (natural language processing), or other sensor data.\n",
      "4.  **Understand and Generate Language:** Process and create human language, allowing for communication and comprehension.\n",
      "5.  **Manipulate and Move:** Interact with the physical world, often through robotics.\n",
      "\n",
      "**Key Concepts and Branches of AI:**\n",
      "\n",
      "*   **Machine Learning (ML):** A subset of AI that focuses on enabling systems to learn from data. Instead of being explicitly programmed for every task, ML algorithms find patterns in data and make predictions or decisions based on those patterns.\n",
      "    *   **Supervised Learning:** Learning from labeled examples (e.g., showing an AI pictures of cats and dogs, labeled as such, so it can identify new ones).\n",
      "    *   **Unsupervised Learning:** Finding patterns in unlabeled data (e.g., grouping similar news articles without being told what the groups should be).\n",
      "    *   **Reinforcement Learning:** Learning by trial and error, receiving rewards or penalties for actions (e.g., an AI learning to play a game by being rewarded for scoring points).\n",
      "*   **Deep Learning (DL):** A subfield of machine learning that uses artificial neural networks with multiple layers (hence \"deep\") to learn complex patterns from vast amounts of data. This is behind many recent breakthroughs in image recognition, natural language processing, and more.\n",
      "*   **Natural Language Processing (NLP):** Enables computers to understand, interpret, and generate human language. Examples include voice assistants, machine translation, and spam filters.\n",
      "*   **Computer Vision (CV):** Allows computers to \"see\" and interpret visual information from the real world, such as images and videos. Used in facial recognition, self-driving cars, and medical imaging analysis.\n",
      "*   **Robotics:** Involves the design, construction, operation, and use of robots. AI often powers the intelligence and decision-making capabilities of these robots.\n",
      "\n",
      "**Types of AI (by Capability):**\n",
      "\n",
      "1.  **Narrow AI (or Weak AI):** This is all the AI that exists today. It's designed and trained for a specific task (e.g., playing chess, recommending movies, facial recognition, language translation). It can perform its specific task exceptionally well, often surpassing human capabilities, but lacks general intelligence.\n",
      "2.  **General AI (AGI or Strong AI):** This is theoretical AI that would possess human-level cognitive abilities across a wide range of tasks, including reasoning, problem-solving, learning from experience, and even demonstrating creativity, much like a human. We are not there yet.\n",
      "3.  **Superintelligence:** A hypothetical AI that would surpass human intelligence across virtually all fields, including scientific creativity, general wisdom, and social skills. This is even further in the future than AGI.\n",
      "\n",
      "**Where do you encounter AI?**\n",
      "\n",
      "*   **Voice Assistants:** Siri, Alexa, Google Assistant\n",
      "*   **Recommendation Systems:** Netflix, Amazon, Spotify\n",
      "*   **Self-driving Cars:** Tesla Autopilot, Waymo\n",
      "*   **Image and Facial Recognition:** Unlocking your phone, tagging friends on social media\n",
      "*   **Spam Filters and Fraud Detection:** Identifying suspicious emails or financial transactions\n",
      "*   **Medical Diagnosis:** Assisting doctors in identifying diseases from scans\n",
      "*   **Chatbots:** Customer service interactions\n",
      "*   **Generative AI:** Tools like ChatGPT for text generation, Midjourney for image creation\n",
      "\n",
      "In essence, AI is about empowering machines to think, learn, and act in ways that mimic or augment human intelligence, allowing them to solve complex problems and perform tasks that were once exclusively the domain of humans. It's a rapidly evolving field with the potential to transform nearly every aspect of our lives.\n"
     ]
    }
   ],
   "source": [
    "import google.generativeai as genai\n",
    "\n",
    "genai.configure(api_key=\"AQ.Ab8RN6Lobh-oQwbNcq-ZdCtk0BklRJwSws4cnEV1Qxa0SU9z1Q\")\n",
    "\n",
    "model = genai.GenerativeModel(\"gemini-2.5-flash\")\n",
    "\n",
    "response = model.generate_content(\"What is AI?\")\n",
    "\n",
    "print(response.text)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "7440bfb2-e2e5-456d-a440-3f4538c16348",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python [conda env:base] *",
   "language": "python",
   "name": "conda-base-py"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.13.5"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
